# **09. 추천 시스템**

## **01. 추천 시스템의 개요와 배경**

###**추천 시스템의 개요**

: 추천 시스템을 통해 사용자의 취향을 이해하고 맞춤 상품과 콘텐츠를 제공해 조금이라도 오래 자기 사이트에 고객을 머무르게 하기 위해 전력을 기울이고 있음.

###**온라인 스토어의 필수 요소, 추천 시스템**

: 한정된 시간이라는 제약을 가진 상황에서 너무 많은 상품과 콘텐츠는 오히려 사용자가 어떤 상품을 골라야 할지에 대한 압박감을 느끼게 만들 수 밖에 없는데, 추천 시스템이 이러한 상황을 타개해줌.

: 온라인 스토어는 많은 양의 고객과 상품 관련 데이터를 가지고 있음. 이 모든 데이터가 사용자가 흥미를 가질 만한 상품을 즉각적으로 추천하는 데 사용.
- 사용자가 어떤 상품을 구매했는가?
- 사용자가 어떤 상품을 둘러보거나 장바구니에 넣었는가?
- 사용자가 평가한 영화 평점은? 제품 평가는?
- 사용자가 스스로 작성한 자신의 취향은?
- 사용자가 무엇을 클릭했는가?

![image.png](images/image_01.png)

###**추천 시스템의 유형**

- 기반 필터링 방식
- 협업 필터링 방식

으로 나뉨. 그리고 협업 필터링 방식은

- 최근접 이웃 협업 필터링
- 잠재 요인 협업 필터링

으로 나뉨.

<br>

##**02. 콘텐츠 기반 필터링 추천 시스템**

: 사용자가 특정한 아이템을 매우 선호하는 경우, 그 아이템과 비슷한 콘텐츠를 가진 다른 아이템을 추천하는 방식.

ex) 사용자가 특정 영화에 높은 평점을 줬다면 그 영화의 장르, 출연 배우, 감독, 영화 키워드 등의 콘텐츠와 유사한 다른 영화를 추천해주는 방식.

![image.png](images/image_02.png)


##**03. 최근접 이웃 협업 필터링**

: 사용자가 아이템에 매긴 평점 정보나 상품 구매 이력과 같은 사용자 행동 양식만을 기반으로 추천을 수행하는 것.

목표) 사용자-아이템 평점 매트릭스와 같은 축적된 사용자 행동 데이터를 기반으로 사용자가 아직 평가하지 않은 아이템을 예측 평가하는 것.

> 즉, 사용자가 평가한 다른 아이템을 기반으로 사용자가 평가하지 않은 아이템의 예측 평가를 도출하는 방법

- 협업 필터링 기반의 추천 시스템은 최근접 이웃 방식과 잠재 요인 방식으로 나뉘며, 두 방식 모두 사용자-아이템 평점 행렬 데이터에만 의지해 추천을 수행.
- 협업 필터링 알고리즘에 사용되는 사용자-아이템 평점 행렬에서 행은 개별 사용자, 열은 개별 아이템으로 구성되며, 사용자 아이디 행, 아이템 아이디 열 위치에 해당하는 값이 평점을 나타내는 형태가 돼야 함.

*** 사용자가 아이템에 대한 평점을 매기는 경우가 많지 않기 때문에 희소 행렬 특성을 가지고 있음.

![image.png](images/image_03.png)

최근접 이웃 협업 필터링은 메모리 협업 필터링이라고도 하며, 일반적으로 사용자 기반과 아이템 기반으로 다시 나뉠 수 있음.

- 사용자 기반(User-User): 당신과 비슷한 고객들이 다음 상품도 구매했습니다.
- 아이템 기반(Item-Item): 이 상품을 선택한 다른 고객들은 다음 상품도 구매했습니다.

------------

사용자 기반 최근접 이웃 방식은 특정 사용자와 유사한 다른 사용자를 Top-N으로 선정해 이 Top-N 사용자가 좋아하는 아이템을 추천하는 방식.

즉, 특정 사용자와 타 사용자 간의 유사도를 측정한 뒤 가장 유사도가 높은 TOP_N 사용자를 추출해 그들이 선호하는 아이템을 추천하는 것.

![image.png](images/image_04.png)

다음 그림은 아이템 기반 최근접 이웃 방식의 기반 데이터 세트. 위의 사용자 기반 최근접 이웃 데이터 세트와 행과 열이 서로 반대.

![image.png](images/image_05.png)

- '다크 나이트'와 '프로메테우스'는 상호 간 아이템 유사도가 상대적으로 매우 높음.
- 따라서 '다크 나이트'를 매우 좋아하는 사용자 D에게 아이템 기반 협업 필터리은 D가 아직 관람하지 못한 '프로메테우스'와 '스타워즈-라스트 제다이' 중 '프로메테우스'를 추천.

<br>

- 일반적으로 사용자 기반보다는 아이템 기반 협업 필터링이 정확도가 더 높음.

- 이유는 비슷한 영화 또는 상품을 좋아한다고 해서 사람들의 취향이 비슷하다고 판단하기는 어려운 경우가 많기 때문.

- 따라서 최근접 이웃 협업 필터링은 대부분 아이템 기반의 알고리즘 적용.

+) 앞장의 텍스트 분석에서 소개된 유사도 측정 방법인 코사인 유사도는 추천 시스템의 유사도 측정에 가장 많이 적용됨. 추천 시스템에 사용되는 데이터는 피처 벡터화된 텍스트 데이터와 동일하게 다차원 희소 행렬이라는 특징이 있으므로 유사도 측정을 위해 주로 코사인 유사도를 이용.

<br>

##**04. 잠재 요인 협업 필터링**

###**잠재 요인 협업 필터링의 이해**

: 사용자 - 아이템 평점 매트릭스 속에 숨어 있는 잠재 요인을 추출해 추천 예측을 할 수 있게 하는 기법.

**행렬 분해**: 대규모 다차원 행렬을 SVD와 같은 차원 감소 기법으로 분해하는 과정에서 잠재 요인을 추출하는 기법.

- 잠재 요인을 기반으로 다차원 희소 행렬인 사용자 - 아이템 행렬 데이터를 저차원 밀집 행렬의 사용자-잠재요인 행렬과 아이템-잠재요인 행렬의 전치행렬로 분해할 수 있음.
- 이렇게 분해된 두 행렬의 내적을 통해 새로운 예측 사용자-아이템 평점 행렬 데이터를 만들어서 사용자가 아직 평점을 부여하지 않는 아이템에 대한 예측 평점을 생성하는 것이 잠재 요인 협력 필터링 알고리즘의 골자.

![image.png](images/image_06.png)

행렬 분해에 의해 추출되는 잠재 요인이 정확히 어떤 것인지는 알 수 없지만, 가령 영화 평점 기반의 사용자-아이템 평점 행렬 데이터라면 영화가 가지는 장르별 특성 선호도로 가정할 수 있음.
- 즉, 사용자-잠재 요인 행렬은 사용자의 영화 장르에 대한 선호도로, 아이템-잠제 요인 행렬은 영화의 장르별 특성값으로 정의할 수 있음.

![image.png](images/image_07.png)

평점이란 사용자의 특정 영화 장르에 대한 선호도와 개별 영화의 그 장르적 특성값을 반영해 결정된다고 할 수 있음.

따라서 평점은 사용자의 장르별 선호도 벡터와 영화의 장르별 특성 벡터를 서로 곱해서 만들 수 있음. 즉, User 1의 item 1의 평점인 R(1,1)의 4점은 P 매트릭스의 User 1 벡터와 Q.T 매트릭스의 Item 1 벡터를 곱한 값.

마찬가지 방법으로, 아직 User 1이 평점을 매기지 못한 Item 2에 대해 예측 평점을 수행해 보면, R(1,2)는 행렬 분해된 P 매트릭스의 User 1 벡터와 Q.T 매트릭스의 Item 2 벡터의 내적 결괏값인 2.56으로 예측할 수 있음.

![image.png](images/image_08.png)

이처럼 잠재 요인 협업 필터링은 숨겨져 있는 잠재 요인을 기반으로 분해된 매트릭스를 이용해 사용자가 아직 평가하지 않은 아이템에 대한 예측 평가를 수행하는 것.

<br>

###**행렬 분해의 이해**

: 다차원의 매트릭스를 저차원 매트릭스로 분해하는 기법으로서 대표적으로 SVD, NMF 등이 있음.

- M개의 사용자 행과 N개의 아이템 열을 가진 평점 행렬은 M X N 차원으로 구성되며, 행렬 분해를 통해 사용자-K 차원 잠재 요인 행렬 P(M X K 차원)와 K 차원 잠재 요인 - 아이탬 행렬 Q.T(K X N 차원)으로 분해될 수 있음.

![image.png](images/image_09.png)

즉, R = P*Q.T



![image.png](images/image_10.png)

![image.png](images/image_11.png)

- 행렬 분해는 주로 SVD 방식을 이용. 하지만 SVD는 NaN 값이 없는 행렬에만 적용할 수 있음.
- 이러한 경우에는 확률적 경사 하강법(SGD)이나 ALS 방식을 이용해 SVD 수행

<br>

###**확률적 경사 하강법을 이용한 행렬 분해**

: P와 Q 행렬로 계산된 예측 R 행렬 값과 가장 최소의 오류를 가질 수 있도록 반복적인 비용 함수 최적화를 통해 P와 Q를 유추해내는 것

1. P와 Q를 임의의 값을 가진 행렬로 설정.
2. P와 Q.T 값을 곱해 R 행렬을 계산하고 예측 R 행렬과 실제 R 행렬에 해당하는 오류 값을 계산.
3. 이 오류 값을 최소화할 수 있도록 P와 Q 행렬을 적절한 값으로 각각 업데이트.
4. 만족할 만한 오류 값을 가질 때까지 2,3번 작업을 반복하면서 P와 Q 값을 업데이트해 근사화함.

[실제 값과 예측값의 오류 최소화와 L2 규제를 고려한 비용 함수식]

![image.png](images/image_12.png)

일반적으로 사용자-아이템 평점 행렬의 경우 행렬 분해를 위해 단순히 예측 오류값의 최소화와 학습 시 과적합을 피하기 위해 규제를 반영한 비용 함수를 적용.

그리고 위의 비용 함수를 최소화하기 위해 새롭게 업데이트되는 벡터

![image.png](images/image_13.png)

![image.png](images/image_14.png)

![image.png](images/image_15.png)

- L2 규제를 반영해 실제 R 행렬 값과 예측 R 행렬 값의 차이를 최소화하는 방향성을 가지고 P행렬과 Q행렬에 업데이트 값을 반복적으로 수행하면서 최적화된 예측 R 행렬을 구하는 방식이 SGD 기반의 행렬 분해.

In [1]:
import numpy as np

# 원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재 요인 차원 K는 3으로 설정.
R = np.array([[4, np.nan, np.nan, 2, np.nan],
              [np.nan, 5, np.nan, 3, 1],
              [np.nan, np.nan, 3, 4, 4],
              [5, 2, 1, 2, np.nan]])

num_users, num_items = R.shape
K = 3

# P와 Q 행렬의 크기를 지정하고 정규 분포를 가진 임의의 값으로 입력합니다.
np.random.seed(1)

P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))

다음으로 실제 R 행렬과 예측 행렬의 오차를 구하는 get_rmse() 함수 만들기

- rmse() 함수는 실제 R 행렬의 널이 아닌 행렬 값의 위치 인덱스를 추출해 이 인덱스에 있는 실제 R 행렬 값과 분해된 P,Q를 이용해 다시 조합된 예측 행렬 값의 RMSE 값을 반환.


In [2]:
from sklearn.metrics import mean_squared_error

def get_rmse(R, P, Q, non_zeros):
    error = 0

    # 두 개의 분해된 행렬 P와 Q.T의 내적으로 예측 R 행렬 생성
    full_pred_matrix = np.dot(P, Q.T)

    # 실제 R 행렬에서 널이 아닌 값의 위치 인덱스 추출해 실제 R 행렬과 예측 행렬의 RMSE 추출
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)

    return rmse

- 이제 SGD 기반으로 행렬 분해 수행.
- steps는 SGD 반복해서 업데이터할 횟수.
- learning_rate는 SGD의 학습률
- r_lambda는 L2 규제 계수

In [3]:
# R > 0인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장.
non_zeros = [(i, j, R[i, j]) for i in range(num_users) for j in range(num_items) if R[i, j] > 0]

steps = 1000
learning_rate = 0.01
r_lambda = 0.01

# SGD 기법으로 P와 Q 매트릭스를 계속 업데이트.
for step in range(steps):
    for i, j, r in non_zeros:
        # 실제 값과 예측 값의 차이인 오류 값 구함
        eij = r - np.dot(P[i, :], Q[j, :].T)
        # Regularization을 반영한 SGD 업데이트 공식 적용
        P[i, :] = P[i, :] + learning_rate * (eij * Q[j, :] - r_lambda*P[i, :])
        Q[j, :] = Q[j, :] + learning_rate * (eij * P[i, :] - r_lambda * Q[j, :])

    rmse = get_rmse(R, P, Q, non_zeros)
    if step % 50 == 0:
        print("### iteration step : ", step, " rmse : ", rmse)

### iteration step :  0  rmse :  3.2388050277987723
### iteration step :  50  rmse :  0.4876723101369648
### iteration step :  100  rmse :  0.1564340384819247
### iteration step :  150  rmse :  0.07455141311978046
### iteration step :  200  rmse :  0.04325226798579314
### iteration step :  250  rmse :  0.029248328780878973
### iteration step :  300  rmse :  0.022621116143829466
### iteration step :  350  rmse :  0.019493636196525135
### iteration step :  400  rmse :  0.018022719092132704
### iteration step :  450  rmse :  0.01731968595344266
### iteration step :  500  rmse :  0.016973657887570753
### iteration step :  550  rmse :  0.016796804595895633
### iteration step :  600  rmse :  0.01670132290188466
### iteration step :  650  rmse :  0.01664473691247669
### iteration step :  700  rmse :  0.016605910068210026
### iteration step :  750  rmse :  0.016574200475705
### iteration step :  800  rmse :  0.01654431582921597
### iteration step :  850  rmse :  0.01651375177473524
### iterati

In [4]:
pred_matrix = np.dot(P, Q.T)
print('예측 행렬:\n', np.round(pred_matrix, 3))

예측 행렬:
 [[3.991 0.897 1.306 2.002 1.663]
 [6.696 4.978 0.979 2.981 1.003]
 [6.677 0.391 2.987 3.977 3.986]
 [4.968 2.005 1.006 2.017 1.14 ]]


원본 행렬과 비교해 널이 아닌 값은 큰 차이가 나지 않으며, 널인 값은 새로운 예측값으로 채워짐.